MODEL_FOLDER_PATH = "models/"

FIELD_SIZE= 8

AGENT_MODEL_FOLDER_PATH = "%sagent/" % MODEL_FOLDER_PATH
AGENT_TEMP_MODEL_PATH = '%sagent_model_temp.h5' % AGENT_MODEL_FOLDER_PATH
AGENT_MODEL_PATH = '%sagent_model.h5' % AGENT_MODEL_FOLDER_PATH
AGENT_MODEL_LOSS_PATH = '%sagent_model_loss.h5' % AGENT_MODEL_FOLDER_PATH
AGENT_MODEL_MAE_PATH = '%sagent_model_mae.h5' % AGENT_MODEL_FOLDER_PATH

TENSORBOARD_LOG_DIR = "logs/fit/"

